"""add new table for telegram seen

Revision ID: 64f5d0dd45c0
Revises: 94c53915b06a
Create Date: 2025-03-13 00:54:00.733594

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "64f5d0dd45c0"
down_revision: Union[str, None] = "94c53915b06a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_seen_telegram_apartments",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("apartment_id", sa.Integer(), nullable=False),
        sa.Column("seen_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["apartment_id"], ["telegram_apartments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "apartment_id"),
    )
    op.create_index(
        op.f("ix_user_seen_telegram_apartments_apartment_id"),
        "user_seen_telegram_apartments",
        ["apartment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_seen_telegram_apartments_user_id"),
        "user_seen_telegram_apartments",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_seen_telegram_apartments_user_id"),
        table_name="user_seen_telegram_apartments",
    )
    op.drop_index(
        op.f("ix_user_seen_telegram_apartments_apartment_id"),
        table_name="user_seen_telegram_apartments",
    )
    op.drop_table("user_seen_telegram_apartments")
    # ### end Alembic commands ###
