"""add telegram scrapping models

Revision ID: 0d785eab7401
Revises: bd98cd0f5d2d
Create Date: 2025-03-09 20:09:25.708826

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0d785eab7401"
down_revision: Union[str, None] = "bd98cd0f5d2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_apartments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("channel_username", sa.String(), nullable=True),
        sa.Column("is_offer", sa.Boolean(), nullable=True),
        sa.Column("is_roommate_offer", sa.Boolean(), nullable=True),
        sa.Column("is_rental_offer", sa.Boolean(), nullable=True),
        sa.Column("monthly_price", sa.String(), nullable=True),
        sa.Column("preferred_gender", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("contact", sa.String(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "telegram_apartment_photos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("apartment_id", sa.Integer(), nullable=False),
        sa.Column("photo_data", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["apartment_id"], ["telegram_apartments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("telegram_apartment_photos")
    op.drop_table("telegram_apartments")
    # ### end Alembic commands ###
