"""set non unique apartment url

Revision ID: c3acd84aab4a
Revises: f0828dfe4426
Create Date: 2025-03-13 23:45:34.038492

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c3acd84aab4a"
down_revision: Union[str, None] = "f0828dfe4426"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("apartments_url_key", "apartments", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("apartments_url_key", "apartments", ["url"])
    # ### end Alembic commands ###
