"""add city for telegram_apartments

Revision ID: 94c53915b06a
Revises: 4017c7036b46
Create Date: 2025-03-12 22:24:28.500825

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "94c53915b06a"
down_revision: Union[str, None] = "4017c7036b46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("telegram_apartments", sa.Column("city", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_telegram_apartments_city"),
        "telegram_apartments",
        ["city"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telegram_apartments_city"), table_name="telegram_apartments")
    op.drop_column("telegram_apartments", "city")
    # ### end Alembic commands ###
