"""add apartment_type for user_seen_apartments

Revision ID: 4017c7036b46
Revises: 0d785eab7401
Create Date: 2025-03-11 09:20:30.302524

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from src.utils.rental_types import RentalTypes


revision: str = "4017c7036b46"
down_revision: Union[str, None] = "0d785eab7401"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_seen_apartments", sa.Column("apartment_type", sa.String(), nullable=True)
    )
    op.execute(
        f"UPDATE user_seen_apartments SET apartment_type = '{RentalTypes.FULL_APARTMENT}'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_seen_apartments", "apartment_type")
    # ### end Alembic commands ###
