"""Initial

Revision ID: d3badc7774c7
Create Date: 2025-03-06 00:21:14.625295

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d3badc7774c7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apartments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("rooms", sa.Integer(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("square", sa.Float(), nullable=True),
        sa.Column("district", sa.String(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("complex_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("filter_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "apartment_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("apartment_id", sa.Integer(), nullable=False),
        sa.Column("photo_data", sa.LargeBinary(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["apartment_id"], ["apartments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_apartment_photos_apartment_id"),
        "apartment_photos",
        ["apartment_id"],
        unique=False,
    )
    op.create_table(
        "full_apartment_filters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("rooms", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("min_price", sa.Float(), nullable=True),
        sa.Column("max_price", sa.Float(), nullable=True),
        sa.Column("min_square", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_full_apartment_filters_user_id"),
        "full_apartment_filters",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "room_sharing_filters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("roommate_preference", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("rooms", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("min_price", sa.Float(), nullable=True),
        sa.Column("max_price", sa.Float(), nullable=True),
        sa.Column("min_square", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_room_sharing_filters_user_id"),
        "room_sharing_filters",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_filters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("rooms", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("min_price", sa.Float(), nullable=True),
        sa.Column("max_price", sa.Float(), nullable=True),
        sa.Column("min_square", sa.Float(), nullable=True),
        sa.Column("rental_type", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("roommate_preference", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_filters_user_id"), "user_filters", ["user_id"], unique=False
    )
    op.create_table(
        "user_seen_apartments",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("apartment_id", sa.Integer(), nullable=False),
        sa.Column("seen_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["apartment_id"], ["apartments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("apartment_id"),
    )
    op.create_index(
        op.f("ix_user_seen_apartments_apartment_id"),
        "user_seen_apartments",
        ["apartment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_seen_apartments_user_id"),
        "user_seen_apartments",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_seen_apartments_user_id"), table_name="user_seen_apartments"
    )
    op.drop_index(
        op.f("ix_user_seen_apartments_apartment_id"), table_name="user_seen_apartments"
    )
    op.drop_table("user_seen_apartments")
    op.drop_index(op.f("ix_user_filters_user_id"), table_name="user_filters")
    op.drop_table("user_filters")
    op.drop_index(
        op.f("ix_room_sharing_filters_user_id"), table_name="room_sharing_filters"
    )
    op.drop_table("room_sharing_filters")
    op.drop_index(
        op.f("ix_full_apartment_filters_user_id"), table_name="full_apartment_filters"
    )
    op.drop_table("full_apartment_filters")
    op.drop_index(
        op.f("ix_apartment_photos_apartment_id"), table_name="apartment_photos"
    )
    op.drop_table("apartment_photos")
    op.drop_table("users")
    op.drop_table("apartments")
    # ### end Alembic commands ###
