"""add number max_price

Revision ID: f0828dfe4426
Revises: 64f5d0dd45c0
Create Date: 2025-03-13 01:13:11.406664

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f0828dfe4426"
down_revision: Union[str, None] = "64f5d0dd45c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            "UPDATE telegram_apartments SET monthly_price = regexp_replace(monthly_price, '[^0-9]', '', 'g') WHERE monthly_price IS NOT NULL"
        )
    )

    # Заменяем пустые строки на NULL
    op.execute(
        sa.text(
            "UPDATE telegram_apartments SET monthly_price = NULL WHERE monthly_price = ''"
        )
    )

    # Теперь можно безопасно преобразовать тип
    op.execute(
        sa.text(
            "ALTER TABLE telegram_apartments ALTER COLUMN monthly_price TYPE INTEGER USING (monthly_price::integer)"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "telegram_apartments",
        "monthly_price",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
